apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: docs-example
  template: docs-example
message: |-
  The following service(s) have been created in your project: ${NAME}.

  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/httpd-ex/blob/master/README.md.
metadata:
  annotations:
    description: An example application which which serves documentation built from compatible
      Mkdocs markdown files via HTTPD server. For more details see https://github.com/tomasliumparas/openshift-mkdocs-ex
    iconClass: fa fa-book
    openshift.io/display-name: Mkdocs
    openshift.io/documentation-url: https://github.com/tomasliumparas/openshift-mkdocs-ex
    openshift.io/long-description: This template defines resources needed to develop
      a static application served by Apache HTTP Server (httpd), including a build
      configuration and application deployment configuration.
    openshift.io/provider-display-name: Tomas Liumparas
    openshift.io/support-url: https://github.com/tomasliumparas/openshift-mkdocs-ex/issues
    tags: quickstart,httpd,docs,pipeline
    template.openshift.io/bindable: "false"
  name: docs-example
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
- apiVersion: v1
  kind: "BuildConfig"
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: >-
        [{"name": "${NAME}", "namespace": "", "kind":
        "DeploymentConfig"}]
    name: ${NAME}-build
  spec:
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
          // placeholder
          pipeline{
            agent {
              node {
                label 'python'
              }
            }
            environment {
                GIT_REPO="${SOURCE_REPOSITORY_URL}"
                GIT_SSL_NO_VERIFY="true"
                GIT_BRANCH="${SOURCE_REPOSITORY_REF}"
                BUILD_CONFIG="${NAME}"
            }
            stages {
              stage('Get Latest Code') {
                steps {
                  git branch: "${GIT_BRANCH}", url: "${GIT_REPO}", credentialsId: "scm-credentials" // declared in environment
                }
              }
              stage("Install build requirements") {
                steps {
                  // Archive the build output artifacts.
                  sh """
                  scl enable rh-python36 'virtualenv --no-site-packages .'
                  source bin/activate
                  python --version
                  pip3 install --upgrade pip
                  pip3 install mkdocs
                  pip3 install mkdocs-material
                  pip3 install pymdown-extensions
                  pip3 install Pygments
                  deactivate
                  """
                }
              }

              stage('Promote to PROD?') {
                steps{
                  input 'Promote to production?'
                }
              }

              stage("Build the docs") {
                steps {
                  sh '''
                  source bin/activate
                  mkdocs build
                  deactivate
                  '''
                }
              }

              stage("Trigger build"){
                steps {
                  sh 'oc start-build ${BUILD_CONFIG} --from-dir=site --follow'
                }
              }

            }
          }
        type: JenkinsPipeline
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: httpd:2.4
          namespace: ${NAMESPACE}
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env: []
          image: ' '
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: ${NAME}
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: docs-example
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: openshift
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/tomasliumparas/openshift-mkdocs-ex.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: The exposed hostname that will route to the httpd service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: A secret string used to configure the Generic webhook.
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
